### ISSUE TITLE
Error in Layer Geek

### ISSUE THREAD

**Issue by schriftlabor-miriam** [mekkablue/LayerGeek#2]
When I open a Glyphsfile with LayerGeek Custom Parameters I constantly get this:

![screen shot 2018-03-14 at 16 11 28](https://user-images.githubusercontent.com/20683245/37413813-1e309e2c-27a8-11e8-83d6-a11fd5da16a2.png)

Macro: 

Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 548, in processLayer_withArguments_
  File "/Users/Miriam/Library/Application Support/Glyphs/Repositories/LayerGeek/LayerGeek.glyphsFilter/Contents/Resources/plugin.py", line 63, in filter
    layerFunctions = [customParameters[x] for x in range(len(customParameters))]
KeyError: 2

**Comment by mekkablue** [comment]
When you open Font Info?

_Update: Could reproduce it, just uploaded a fix, thx for reporting._
